<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>XML Sitemap</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 8px 12px; border-bottom: 1px solid #ccc; }
        th { background-color: #f0f0f0; text-align: left; }
        a { color: #0645AD; text-decoration: none; }
    </style>
</head>
<body>
    <h1>XML Sitemap</h1>
    <p>Generated by <strong>Laravel</strong>, this is an XML Sitemap meant for consumption by search engines.</p>
    <p>You can find more information about XML sitemaps on <a href="https://www.sitemaps.org/" target="_blank">sitemaps.org</a>.</p>
    <p>This XML Sitemap Index file contains {{ count($sitemaps) }} sitemaps.</p>

    <table>
        <thead>
            <tr>
                <th>Sitemap</th>
                <th>Last Modified</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($sitemaps as $map)
                <tr>
                    <td><a href="{{ $map['url'] }}" target="_blank">{{ $map['url'] }}</a></td>
                    <td>{{ $map['lastmod'] }}</td>
                </tr>
                <tr>{{ $latestDate->format('d-m-Y') }} ({{ $latestDate->diffForHumans() }})</tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
